### ISSUE TITLE
Interactive Label doesn't work w/Safari

### ISSUE THREAD

**Issue by nvlgzr** [alex-knyaz/Miscellaneous-svelte-components#1]
Was just messing with your [demo site](https://alex-knyaz.github.io/Miscellaneous-svelte-components/), and found that, while it worked once I reloaded it in Chrome, it failed in Safari (macOS 12.2.1, Safari 15.3). Thought you might want to know.

**Comment by alex-knyaz** [comment]
Thanks. Fixed it in the latest commit.

**Comment by nvlgzr** [comment]
Nicely done! Was going to write up a feature request to support Figma-style wrap-around when the cursor hits the screen edge, then figured out that that's only in their desktop app, so presumably there's no web API that would allow such a thing. ¯\\\_(ツ)_/¯

This is one of my favorite features, and it's still super rare to see it in the wild. Thanks for making and sharing this!

**Comment by alex-knyaz** [comment]
Thanks. Wrap-around feature can be implemented using [pointer lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API), but in that case the cursor is hidden.
